name: Validate - Signoz

on: pull_request

jobs:
  validate:
    name: validate
    runs-on: [self-hosted]
    timeout-minutes: 10
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Use Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install yarn
        run: npm install -g yarn

      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile

      - name: Build Application
        run: yarn production:build

